### PR TITLE
Release 0.5.7

### PR DESCRIPTION
**Pull request by blootsvoets**
- Fixes CRITICAL bug that prevented questionnaire data to be submitted (arrays could not properly be processed) - 5ecffe6
- Updates dependencies

### CODE REVIEW

**Comment by yatharthranjan** [comment]
Which version was this introduced in?

**Comment by blootsvoets** [comment]
As far as I can tell, it was introduced in version 0.5.0. It's immediately apparent when trying to upload questionnaire data, since no such data will be accepted (500 error).

**Review by nivemaham — APPROVED** [review]
LGTM. Was this introduced recently? Do we have to deprecate any old version(s)?

**Comment by blootsvoets** [comment]
It was introduces quite long ago: 13 Jul 2020. Older versions will have to be deprecated.

**Pull request merged**
